# Generated by Django 4.2.5 on 2023-09-20 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название блога')),
                ('body', models.TextField(verbose_name='Содержимое блога')),
                ('published_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата публикации.')),
                ('view_count', models.IntegerField(default=0, verbose_name='количество просмотров.')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='изображение.')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
